name = "sixlets-pwa"
pages_build_output_dir = "public"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "sixlets-db"
database_id = "7f51424d-8f1b-4ee1-a5d1-c79ce6f41a9e"
preview_database_id = "7f51424d-8f1b-4ee1-a5d1-c79ce6f41a9e"
